# Generated by Django 4.0.3 on 2023-01-23 18:35

import adsmanager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=adsmanager.models.PathAndRename('ads'))),
                ('target_link', models.URLField()),
                ('link_text', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('sleep_time_minutes', models.PositiveIntegerField(default=5)),
                ('open_new_window', models.BooleanField(default=True)),
                ('active_from_time', models.DateTimeField(blank=True, null=True)),
                ('active_to_time', models.DateTimeField(blank=True, null=True)),
                ('display_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('accept_language', models.CharField(blank=True, max_length=50, null=True)),
                ('referer', models.CharField(blank=True, max_length=150, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clicks', to='adsmanager.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicked_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
