# Generated by Django 4.1.5 on 2023-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adsmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="show_link_text",
            field=models.BooleanField(default=True),
        ),
    ]
